# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 764d8e71f40f6ec217abf84b2411cd154959a1c22ef5d426284a53c3c54da1f4598cbde0906d5a5088068a2255fc597eb203ceab81c070b74cdbf547fd66ed83

test:
  secret_key_base: a41012801c4bddd86a97f8c1c08a869b2f51529464dd714fc68c8ac85470fe397541da6870d566def00a996b28c0214b81444a7ac4a649d62222ddc56d487b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
